### ISSUE TITLE
Document jinja_custom_elements_names

### ISSUE THREAD

**Issue by di** [thibaudcolas/curlylint#25]
### Is your proposal related to a problem?

I tried using curlylint on a project that uses [Jinja's i18n extension](https://jinja.palletsprojects.com/en/2.11.x/extensions/#i18n-extension). Without configuring or changing anything, I would get failures like this:

```
$ cat test.html
{% trans %}
project
{% pluralize %}
projects
{% endtrans %}

$ curlylint test.html
test.html
2:3	Parse error: expected one of 'autoescape', 'block', 'blocktrans', 'comment', 'filter', 'for', 'if', 'ifchanged', 'ifequal', 'ifnotequal', 'not an intermediate Jinja tag name', 'spaceless', 'verbatim', 'with' at 2:3	parse_error

Oh no! 💥 💔 💥
1 error reported
```

I couldn't find any documentation about configuring support for custom elements.

In order to get this to work, I had to a) read the source code to determine if this was possible b) add the following to my `pyproject.toml`:

```toml
[tool.curlylint]
jinja_custom_elements_names = [['trans', 'pluralize', 'endtrans']]
```

### Describe the solution you’d like

Ideally `jinja_custom_elements_names` would be documented / officially supported. The format (a list of lists) should also be explained -- it seems that order is important.

### Additional context

I also discovered that with a sufficiently large directory of templates, naively adding a string instead of a list, e.g.:

```toml
[tool.curlylint]
jinja_custom_elements_names = ['trans']
```
would result in a significant (exponential?) increase in runtime, and should probably be guarded against.
